export const COUNTRY_CODES = [
  { "name": "United States", "code": "US", "emoji": "🇺🇸", "dial_code": "+1" },
  { "name": "United Kingdom", "code": "GB", "emoji": "🇬🇧", "dial_code": "+44" },
  { "name": "Canada", "code": "CA", "emoji": "🇨🇦", "dial_code": "+1" },
  { "name": "Australia", "code": "AU", "emoji": "🇦🇺", "dial_code": "+61" },
  { "name": "Afghanistan", "code": "AF", "emoji": "🇦🇫", "dial_code": "+93" },
  { "name": "Albania", "code": "AL", "emoji": "🇦🇱", "dial_code": "+355" },
  { "name": "Algeria", "code": "DZ", "emoji": "🇩🇿", "dial_code": "+213" },
  { "name": "Andorra", "code": "AD", "emoji": "🇦🇩", "dial_code": "+376" },
  { "name": "Angola", "code": "AO", "emoji": "🇦🇴", "dial_code": "+244" },
  { "name": "Anguilla", "code": "AI", "emoji": "🇦🇮", "dial_code": "+1264" },
  { "name": "Antigua & Barbuda", "code": "AG", "emoji": "🇦🇬", "dial_code": "+1268" },
  { "name": "Argentina", "code": "AR", "emoji": "🇦🇷", "dial_code": "+54" },
  { "name": "Armenia", "code": "AM", "emoji": "🇦🇲", "dial_code": "+374" },
  { "name": "Aruba", "code": "AW", "emoji": "🇦🇼", "dial_code": "+297" },
  { "name": "Austria", "code": "AT", "emoji": "🇦🇹", "dial_code": "+43" },
  { "name": "Azerbaijan", "code": "AZ", "emoji": "🇦🇿", "dial_code": "+994" },
  { "name": "Bahamas", "code": "BS", "emoji": "🇧🇸", "dial_code": "+1242" },
  { "name": "Bahrain", "code": "BH", "emoji": "🇧🇭", "dial_code": "+973" },
  { "name": "Bangladesh", "code": "BD", "emoji": "🇧🇩", "dial_code": "+880" },
  { "name": "Barbados", "code": "BB", "emoji": "🇧🇧", "dial_code": "+1246" },
  { "name": "Belarus", "code": "BY", "emoji": "🇧🇾", "dial_code": "+375" },
  { "name": "Belgium", "code": "BE", "emoji": "🇧🇪", "dial_code": "+32" },
  { "name": "Belize", "code": "BZ", "emoji": "🇧🇿", "dial_code": "+501" },
  { "name": "Benin", "code": "BJ", "emoji": "🇧🇯", "dial_code": "+229" },
  { "name": "Bermuda", "code": "BM", "emoji": "🇧🇲", "dial_code": "+1441" },
  { "name": "Bhutan", "code": "BT", "emoji": "🇧🇹", "dial_code": "+975" },
  { "name": "Bolivia", "code": "BO", "emoji": "🇧🇴", "dial_code": "+591" },
  { "name": "Bosnia & Herzegovina", "code": "BA", "emoji": "🇧🇦", "dial_code": "+387" },
  { "name": "Botswana", "code": "BW", "emoji": "🇧🇼", "dial_code": "+267" },
  { "name": "Brazil", "code": "BR", "emoji": "🇧🇷", "dial_code": "+55" },
  { "name": "Brunei", "code": "BN", "emoji": "🇧🇳", "dial_code": "+673" },
  { "name": "Bulgaria", "code": "BG", "emoji": "🇧🇬", "dial_code": "+359" },
  { "name": "Burkina Faso", "code": "BF", "emoji": "🇧🇫", "dial_code": "+226" },
  { "name": "Burundi", "code": "BI", "emoji": "🇧🇮", "dial_code": "+257" },
  { "name": "Cambodia", "code": "KH", "emoji": "🇰🇭", "dial_code": "+855" },
  { "name": "Cameroon", "code": "CM", "emoji": "🇨🇲", "dial_code": "+237" },
  { "name": "Cape Verde", "code": "CV", "emoji": "🇨🇻", "dial_code": "+238" },
  { "name": "Cayman Islands", "code": "KY", "emoji": "🇰🇾", "dial_code": "+345" },
  { "name": "Central African Republic", "code": "CF", "emoji": "🇨🇫", "dial_code": "+236" },
  { "name": "Chad", "code": "TD", "emoji": "🇹🇩", "dial_code": "+235" },
  { "name": "Chile", "code": "CL", "emoji": "🇨🇱", "dial_code": "+56" },
  { "name": "China", "code": "CN", "emoji": "🇨🇳", "dial_code": "+86" },
  { "name": "Colombia", "code": "CO", "emoji": "🇨🇴", "dial_code": "+57" },
  { "name": "Comoros", "code": "KM", "emoji": "🇰🇲", "dial_code": "+269" },
  { "name": "Congo - Brazzaville", "code": "CG", "emoji": "🇨🇬", "dial_code": "+242" },
  { "name": "Congo - Kinshasa", "code": "CD", "emoji": "🇨🇩", "dial_code": "+243" },
  { "name": "Cook Islands", "code": "CK", "emoji": "🇨🇰", "dial_code": "+682" },
  { "name": "Costa Rica", "code": "CR", "emoji": "🇨🇷", "dial_code": "+506" },
  { "name": "Côte d'Ivoire", "code": "CI", "emoji": "🇨🇮", "dial_code": "+225" },
  { "name": "Croatia", "code": "HR", "emoji": "🇭🇷", "dial_code": "+385" },
  { "name": "Cuba", "code": "CU", "emoji": "🇨🇺", "dial_code": "+53" },
  { "name": "Cyprus", "code": "CY", "emoji": "🇨🇾", "dial_code": "+357" },
  { "name": "Czechia", "code": "CZ", "emoji": "🇨🇿", "dial_code": "+420" },
  { "name": "Denmark", "code": "DK", "emoji": "🇩🇰", "dial_code": "+45" },
  { "name": "Djibouti", "code": "DJ", "emoji": "🇩🇯", "dial_code": "+253" },
  { "name": "Dominica", "code": "DM", "emoji": "🇩🇲", "dial_code": "+1767" },
  { "name": "Dominican Republic", "code": "DO", "emoji": "🇩🇴", "dial_code": "+1849" },
  { "name": "Ecuador", "code": "EC", "emoji": "🇪🇨", "dial_code": "+593" },
  { "name": "Egypt", "code": "EG", "emoji": "🇪🇬", "dial_code": "+20" },
  { "name": "El Salvador", "code": "SV", "emoji": "🇸🇻", "dial_code": "+503" },
  { "name": "Equatorial Guinea", "code": "GQ", "emoji": "🇬🇶", "dial_code": "+240" },
  { "name": "Eritrea", "code": "ER", "emoji": "🇪🇷", "dial_code": "+291" },
  { "name": "Estonia", "code": "EE", "emoji": "🇪🇪", "dial_code": "+372" },
  { "name": "Eswatini", "code": "SZ", "emoji": "🇸🇿", "dial_code": "+268" },
  { "name": "Ethiopia", "code": "ET", "emoji": "🇪🇹", "dial_code": "+251" },
  { "name": "Fiji", "code": "FJ", "emoji": "🇫🇯", "dial_code": "+679" },
  { "name": "Finland", "code": "FI", "emoji": "🇫🇮", "dial_code": "+358" },
  { "name": "France", "code": "FR", "emoji": "🇫🇷", "dial_code": "+33" },
  { "name": "French Guiana", "code": "GF", "emoji": "🇬🇫", "dial_code": "+594" },
  { "name": "French Polynesia", "code": "PF", "emoji": "🇵🇫", "dial_code": "+689" },
  { "name": "Gabon", "code": "GA", "emoji": "🇬🇦", "dial_code": "+241" },
  { "name": "Gambia", "code": "GM", "emoji": "🇬🇲", "dial_code": "+220" },
  { "name": "Georgia", "code": "GE", "emoji": "🇬🇪", "dial_code": "+995" },
  { "name": "Germany", "code": "DE", "emoji": "🇩🇪", "dial_code": "+49" },
  { "name": "Ghana", "code": "GH", "emoji": "🇬🇭", "dial_code": "+233" },
  { "name": "Gibraltar", "code": "GI", "emoji": "🇬🇮", "dial_code": "+350" },
  { "name": "Greece", "code": "GR", "emoji": "🇬🇷", "dial_code": "+30" },
  { "name": "Greenland", "code": "GL", "emoji": "🇬🇱", "dial_code": "+299" },
  { "name": "Grenada", "code": "GD", "emoji": "🇬🇩", "dial_code": "+1473" },
  { "name": "Guadeloupe", "code": "GP", "emoji": "🇬🇵", "dial_code": "+590" },
  { "name": "Guam", "code": "GU", "emoji": "🇬🇺", "dial_code": "+1671" },
  { "name": "Guatemala", "code": "GT", "emoji": "🇬🇹", "dial_code": "+502" },
  { "name": "Guinea", "code": "GN", "emoji": "🇬🇳", "dial_code": "+224" },
  { "name": "Guinea-Bissau", "code": "GW", "emoji": "🇬🇼", "dial_code": "+245" },
  { "name": "Guyana", "code": "GY", "emoji": "🇬🇾", "dial_code": "+595" },
  { "name": "Haiti", "code": "HT", "emoji": "🇭🇹", "dial_code": "+509" },
  { "name": "Honduras", "code": "HN", "emoji": "🇭🇳", "dial_code": "+504" },
  { "name": "Hong Kong SAR China", "code": "HK", "emoji": "🇭🇰", "dial_code": "+852" },
  { "name": "Hungary", "code": "HU", "emoji": "🇭🇺", "dial_code": "+36" },
  { "name": "Iceland", "code": "IS", "emoji": "🇮🇸", "dial_code": "+354" },
  { "name": "India", "code": "IN", "emoji": "🇮🇳", "dial_code": "+91" },
  { "name": "Indonesia", "code": "ID", "emoji": "🇮🇩", "dial_code": "+62" },
  { "name": "Iran", "code": "IR", "emoji": "🇮🇷", "dial_code": "+98" },
  { "name": "Iraq", "code": "IQ", "emoji": "🇮🇶", "dial_code": "+964" },
  { "name": "Ireland", "code": "IE", "emoji": "🇮🇪", "dial_code": "+353" },
  { "name": "Israel", "code": "IL", "emoji": "🇮🇱", "dial_code": "+972" },
  { "name": "Italy", "code": "IT", "emoji": "🇮🇹", "dial_code": "+39" },
  { "name": "Jamaica", "code": "JM", "emoji": "🇯🇲", "dial_code": "+1876" },
  { "name": "Japan", "code": "JP", "emoji": "🇯🇵", "dial_code": "+81" },
  { "name": "Jordan", "code": "JO", "emoji": "🇯🇴", "dial_code": "+962" },
  { "name": "Kazakhstan", "code": "KZ", "emoji": "🇰🇿", "dial_code": "+77" },
  { "name": "Kenya", "code": "KE", "emoji": "🇰🇪", "dial_code": "+254" },
  { "name": "Kiribati", "code": "KI", "emoji": "🇰🇮", "dial_code": "+686" },
  { "name": "Kuwait", "code": "KW", "emoji": "🇰🇼", "dial_code": "+965" },
  { "name": "Kyrgyzstan", "code": "KG", "emoji": "🇰🇬", "dial_code": "+996" },
  { "name": "Laos", "code": "LA", "emoji": "🇱🇦", "dial_code": "+856" },
  { "name": "Latvia", "code": "LV", "emoji": "🇱🇻", "dial_code": "+371" },
  { "name": "Lebanon", "code": "LB", "emoji": "🇱🇧", "dial_code": "+961" },
  { "name": "Lesotho", "code": "LS", "emoji": "🇱🇸", "dial_code": "+266" },
  { "name": "Liberia", "code": "LR", "emoji": "🇱🇷", "dial_code": "+231" },
  { "name": "Libya", "code": "LY", "emoji": "🇱🇾", "dial_code": "+218" },
  { "name": "Liechtenstein", "code": "LI", "emoji": "🇱🇮", "dial_code": "+423" },
  { "name": "Lithuania", "code": "LT", "emoji": "🇱🇹", "dial_code": "+370" },
  { "name": "Luxembourg", "code": "LU", "emoji": "🇱🇺", "dial_code": "+352" },
  { "name": "Madagascar", "code": "MG", "emoji": "🇲🇬", "dial_code": "+261" },
  { "name": "Malawi", "code": "MW", "emoji": "🇲🇼", "dial_code": "+265" },
  { "name": "Malaysia", "code": "MY", "emoji": "🇲🇾", "dial_code": "+60" },
  { "name": "Maldives", "code": "MV", "emoji": "🇲🇻", "dial_code": "+960" },
  { "name": "Mali", "code": "ML", "emoji": "🇲🇱", "dial_code": "+223" },
  { "name": "Malta", "code": "MT", "emoji": "🇲🇹", "dial_code": "+356" },
  { "name": "Mauritania", "code": "MR", "emoji": "🇲🇷", "dial_code": "+222" },
  { "name": "Mauritius", "code": "MU", "emoji": "🇲🇺", "dial_code": "+230" },
  { "name": "Mexico", "code": "MX", "emoji": "🇲🇽", "dial_code": "+52" },
  { "name": "Micronesia", "code": "FM", "emoji": "🇫🇲", "dial_code": "+691" },
  { "name": "Moldova", "code": "MD", "emoji": "🇲🇩", "dial_code": "+373" },
  { "name": "Monaco", "code": "MC", "emoji": "🇲🇨", "dial_code": "+377" },
  { "name": "Mongolia", "code": "MN", "emoji": "🇲🇳", "dial_code": "+976" },
  { "name": "Montenegro", "code": "ME", "emoji": "🇲🇪", "dial_code": "+382" },
  { "name": "Morocco", "code": "MA", "emoji": "🇲🇦", "dial_code": "+212" },
  { "name": "Mozambique", "code": "MZ", "emoji": "🇲🇿", "dial_code": "+258" },
  { "name": "Myanmar (Burma)", "code": "MM", "emoji": "🇲🇲", "dial_code": "+95" },
  { "name": "Namibia", "code": "NA", "emoji": "🇳🇦", "dial_code": "+264" },
  { "name": "Nepal", "code": "NP", "emoji": "🇳🇵", "dial_code": "+977" },
  { "name": "Netherlands", "code": "NL", "emoji": "🇳🇱", "dial_code": "+31" },
  { "name": "New Caledonia", "code": "NC", "emoji": "🇳🇨", "dial_code": "+687" },
  { "name": "New Zealand", "code": "NZ", "emoji": "🇳🇿", "dial_code": "+64" },
  { "name": "Nicaragua", "code": "NI", "emoji": "🇳🇮", "dial_code": "+505" },
  { "name": "Niger", "code": "NE", "emoji": "🇳🇪", "dial_code": "+227" },
  { "name": "Nigeria", "code": "NG", "emoji": "🇳🇬", "dial_code": "+234" },
  { "name": "North Korea", "code": "KP", "emoji": "🇰🇵", "dial_code": "+850" },
  { "name": "North Macedonia", "code": "MK", "emoji": "🇲🇰", "dial_code": "+389" },
  { "name": "Norway", "code": "NO", "emoji": "🇳🇴", "dial_code": "+47" },
  { "name": "Oman", "code": "OM", "emoji": "🇴🇲", "dial_code": "+968" },
  { "name": "Pakistan", "code": "PK", "emoji": "🇵🇰", "dial_code": "+92" },
  { "name": "Palau", "code": "PW", "emoji": "🇵🇼", "dial_code": "+680" },
  { "name": "Palestinian Territories", "code": "PS", "emoji": "🇵🇸", "dial_code": "+970" },
  { "name": "Panama", "code": "PA", "emoji": "🇵🇦", "dial_code": "+507" },
  { "name": "Papua New Guinea", "code": "PG", "emoji": "🇵🇬", "dial_code": "+675" },
  { "name": "Paraguay", "code": "PY", "emoji": "🇵🇾", "dial_code": "+595" },
  { "name": "Peru", "code": "PE", "emoji": "🇵🇪", "dial_code": "+51" },
  { "name": "Philippines", "code": "PH", "emoji": "🇵🇭", "dial_code": "+63" },
  { "name": "Poland", "code": "PL", "emoji": "🇵🇱", "dial_code": "+48" },
  { "name": "Portugal", "code": "PT", "emoji": "🇵🇹", "dial_code": "+351" },
  { "name": "Puerto Rico", "code": "PR", "emoji": "🇵🇷", "dial_code": "+1939" },
  { "name": "Qatar", "code": "QA", "emoji": "🇶🇦", "dial_code": "+974" },
  { "name": "Romania", "code": "RO", "emoji": "🇷🇴", "dial_code": "+40" },
  { "name": "Russia", "code": "RU", "emoji": "🇷🇺", "dial_code": "+7" },
  { "name": "Rwanda", "code": "RW", "emoji": "🇷🇼", "dial_code": "+250" },
  { "name": "Samoa", "code": "WS", "emoji": "🇼🇸", "dial_code": "+685" },
  { "name": "San Marino", "code": "SM", "emoji": "🇸🇲", "dial_code": "+378" },
  { "name": "Saudi Arabia", "code": "SA", "emoji": "🇸🇦", "dial_code": "+966" },
  { "name": "Senegal", "code": "SN", "emoji": "🇸🇳", "dial_code": "+221" },
  { "name": "Serbia", "code": "RS", "emoji": "🇷🇸", "dial_code": "+381" },
  { "name": "Seychelles", "code": "SC", "emoji": "🇸🇨", "dial_code": "+248" },
  { "name": "Sierra Leone", "code": "SL", "emoji": "🇸🇱", "dial_code": "+232" },
  { "name": "Singapore", "code": "SG", "emoji": "🇸🇬", "dial_code": "+65" },
  { "name": "Slovakia", "code": "SK", "emoji": "🇸🇰", "dial_code": "+421" },
  { "name": "Slovenia", "code": "SI", "emoji": "🇸🇮", "dial_code": "+386" },
  { "name": "Solomon Islands", "code": "SB", "emoji": "🇸🇧", "dial_code": "+677" },
  { "name": "Somalia", "code": "SO", "emoji": "🇸🇴", "dial_code": "+252" },
  { "name": "South Africa", "code": "ZA", "emoji": "🇿🇦", "dial_code": "+27" },
  { "name": "South Korea", "code": "KR", "emoji": "🇰🇷", "dial_code": "+82" },
  { "name": "South Sudan", "code": "SS", "emoji": "🇸🇸", "dial_code": "+211" },
  { "name": "Spain", "code": "ES", "emoji": "🇪🇸", "dial_code": "+34" },
  { "name": "Sri Lanka", "code": "LK", "emoji": "🇱🇰", "dial_code": "+94" },
  { "name": "Sudan", "code": "SD", "emoji": "🇸🇩", "dial_code": "+249" },
  { "name": "Suriname", "code": "SR", "emoji": "🇸🇷", "dial_code": "+597" },
  { "name": "Sweden", "code": "SE", "emoji": "🇸🇪", "dial_code": "+46" },
  { "name": "Switzerland", "code": "CH", "emoji": "🇨🇭", "dial_code": "+41" },
  { "name": "Syria", "code": "SY", "emoji": "🇸🇾", "dial_code": "+963" },
  { "name": "Taiwan", "code": "TW", "emoji": "🇹🇼", "dial_code": "+886" },
  { "name": "Tajikistan", "code": "TJ", "emoji": "🇹🇯", "dial_code": "+992" },
  { "name": "Tanzania", "code": "TZ", "emoji": "🇹🇿", "dial_code": "+255" },
  { "name": "Thailand", "code": "TH", "emoji": "🇹🇭", "dial_code": "+66" },
  { "name": "Timor-Leste", "code": "TL", "emoji": "🇹🇱", "dial_code": "+670" },
  { "name": "Togo", "code": "TG", "emoji": "🇹🇬", "dial_code": "+228" },
  { "name": "Tonga", "code": "TO", "emoji": "🇹🇴", "dial_code": "+676" },
  { "name": "Trinidad & Tobago", "code": "TT", "emoji": "🇹🇹", "dial_code": "+1868" },
  { "name": "Tunisia", "code": "TN", "emoji": "🇹🇳", "dial_code": "+216" },
  { "name": "Turkey", "code": "TR", "emoji": "🇹🇷", "dial_code": "+90" },
  { "name": "Turkmenistan", "code": "TM", "emoji": "🇹🇲", "dial_code": "+993" },
  { "name": "Turks & Caicos Islands", "code": "TC", "emoji": "🇹🇨", "dial_code": "+1649" },
  { "name": "Tuvalu", "code": "TV", "emoji": "🇹🇻", "dial_code": "+688" },
  { "name": "Uganda", "code": "UG", "emoji": "🇺🇬", "dial_code": "+256" },
  { "name": "Ukraine", "code": "UA", "emoji": "🇺🇦", "dial_code": "+380" },
  { "name": "United Arab Emirates", "code": "AE", "emoji": "🇦🇪", "dial_code": "+971" },
  { "name": "Uruguay", "code": "UY", "emoji": "🇺🇾", "dial_code": "+598" },
  { "name": "Uzbekistan", "code": "UZ", "emoji": "🇺🇿", "dial_code": "+998" },
  { "name": "Vanuatu", "code": "VU", "emoji": "🇻🇺", "dial_code": "+678" },
  { "name": "Vatican City", "code": "VA", "emoji": "🇻🇦", "dial_code": "+379" },
  { "name": "Venezuela", "code": "VE", "emoji": "🇻🇪", "dial_code": "+58" },
  { "name": "Vietnam", "code": "VN", "emoji": "🇻🇳", "dial_code": "+84" },
  { "name": "Yemen", "code": "YE", "emoji": "🇾🇪", "dial_code": "+967" },
  { "name": "Zambia", "code": "ZM", "emoji": "🇿🇲", "dial_code": "+260" },
  { "name": "Zimbabwe", "code": "ZW", "emoji": "🇿🇼", "dial_code": "+263" }
];