export const TIMEZONES = [
  { "value": "Dateline Standard Time", "text": "(UTC-12:00) International Date Line West", "offset": -12 },
  { "value": "UTC-11", "text": "(UTC-11:00) Coordinated Universal Time-11", "offset": -11 },
  { "value": "Hawaiian Standard Time", "text": "(UTC-10:00) Hawaii", "offset": -10 },
  { "value": "Alaskan Standard Time", "text": "(UTC-09:00) Alaska", "offset": -8 },
  { "value": "Pacific Standard Time (Mexico)", "text": "(UTC-08:00) Baja California", "offset": -7 },
  { "value": "Pacific Standard Time", "text": "(UTC-08:00) Pacific Time (US & Canada)", "offset": -8 },
  { "value": "US Mountain Standard Time", "text": "(UTC-07:00) Arizona", "offset": -7 },
  { "value": "Mountain Standard Time (Mexico)", "text": "(UTC-07:00) Chihuahua, La Paz, Mazatlan", "offset": -6 },
  { "value": "Mountain Standard Time", "text": "(UTC-07:00) Mountain Time (US & Canada)", "offset": -6 },
  { "value": "Central America Standard Time", "text": "(UTC-06:00) Central America", "offset": -6 },
  { "value": "Central Standard Time", "text": "(UTC-06:00) Central Time (US & Canada)", "offset": -5 },
  { "value": "Central Standard Time (Mexico)", "text": "(UTC-06:00) Guadalajara, Mexico City, Monterrey", "offset": -5 },
  { "value": "Canada Central Standard Time", "text": "(UTC-06:00) Saskatchewan", "offset": -6 },
  { "value": "SA Pacific Standard Time", "text": "(UTC-05:00) Bogota, Lima, Quito", "offset": -5 },
  { "value": "Eastern Standard Time", "text": "(UTC-05:00) Eastern Time (US & Canada)", "offset": -5 },
  { "value": "US Eastern Standard Time", "text": "(UTC-05:00) Indiana (East)", "offset": -5 },
  { "value": "Venezuela Standard Time", "text": "(UTC-04:30) Caracas", "offset": -4.5 },
  { "value": "Paraguay Standard Time", "text": "(UTC-04:00) Asuncion", "offset": -4 },
  { "value": "Atlantic Standard Time", "text": "(UTC-04:00) Atlantic Time (Canada)", "offset": -3 },
  { "value": "Central Brazilian Standard Time", "text": "(UTC-04:00) Cuiaba", "offset": -4 },
  { "value": "SA Western Standard Time", "text": "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan", "offset": -4 },
  { "value": "Pacific SA Standard Time", "text": "(UTC-04:00) Santiago", "offset": -4 },
  { "value": "Newfoundland Standard Time", "text": "(UTC-03:30) Newfoundland", "offset": -2.5 },
  { "value": "E. South America Standard Time", "text": "(UTC-03:00) Brasilia", "offset": -3 },
  { "value": "Argentina Standard Time", "text": "(UTC-03:00) Buenos Aires", "offset": -3 },
  { "value": "SA Eastern Standard Time", "text": "(UTC-03:00) Cayenne, Fortaleza", "offset": -3 },
  { "value": "Greenland Standard Time", "text": "(UTC-03:00) Greenland", "offset": -3 },
  { "value": "Montevideo Standard Time", "text": "(UTC-03:00) Montevideo", "offset": -3 },
  { "value": "Bahia Standard Time", "text": "(UTC-03:00) Salvador", "offset": -3 },
  { "value": "UTC-02", "text": "(UTC-02:00) Coordinated Universal Time-02", "offset": -2 },
  { "value": "Azores Standard Time", "text": "(UTC-01:00) Azores", "offset": 0 },
  { "value": "Cape Verde Standard Time", "text": "(UTC-01:00) Cape Verde Is.", "offset": -1 },
  { "value": "Morocco Standard Time", "text": "(UTC) Casablanca", "offset": 1 },
  { "value": "UTC", "text": "(UTC) Coordinated Universal Time", "offset": 0 },
  { "value": "GMT Standard Time", "text": "(UTC) Edinburgh, London", "offset": 0 },
  { "value": "Greenwich Standard Time", "text": "(UTC) Monrovia, Reykjavik", "offset": 0 },
  { "value": "W. Europe Standard Time", "text": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna", "offset": 2 },
  { "value": "Central Europe Standard Time", "text": "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague", "offset": 2 },
  { "value": "Romance Standard Time", "text": "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris", "offset": 2 },
  { "value": "Central European Standard Time", "text": "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb", "offset": 2 },
  { "value": "W. Central Africa Standard Time", "text": "(UTC+01:00) West Central Africa", "offset": 1 },
  { "value": "Namibia Standard Time", "text": "(UTC+01:00) Windhoek", "offset": 1 },
  { "value": "GTB Standard Time", "text": "(UTC+02:00) Athens, Bucharest", "offset": 3 },
  { "value": "Middle East Standard Time", "text": "(UTC+02:00) Beirut", "offset": 3 },
  { "value": "Egypt Standard Time", "text": "(UTC+02:00) Cairo", "offset": 2 },
  { "value": "Syria Standard Time", "text": "(UTC+02:00) Damascus", "offset": 3 },
  { "value": "E. Europe Standard Time", "text": "(UTC+02:00) E. Europe", "offset": 3 },
  { "value": "South Africa Standard Time", "text": "(UTC+02:00) Harare, Pretoria", "offset": 2 },
  { "value": "FLE Standard Time", "text": "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius", "offset": 3 },
  { "value": "Turkey Standard Time", "text": "(UTC+03:00) Istanbul", "offset": 3 },
  { "value": "Israel Standard Time", "text": "(UTC+02:00) Jerusalem", "offset": 3 },
  { "value": "Libya Standard Time", "text": "(UTC+02:00) Tripoli", "offset": 2 },
  { "value": "Jordan Standard Time", "text": "(UTC+03:00) Amman", "offset": 3 },
  { "value": "Arabic Standard Time", "text": "(UTC+03:00) Baghdad", "offset": 3 },
  { "value": "Kaliningrad Standard Time", "text": "(UTC+02:00) Kaliningrad", "offset": 3 },
  { "value": "Arab Standard Time", "text": "(UTC+03:00) Kuwait, Riyadh", "offset": 3 },
  { "value": "E. Africa Standard Time", "text": "(UTC+03:00) Nairobi", "offset": 3 },
  { "value": "Moscow Standard Time", "text": "(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk", "offset": 3 },
  { "value": "Samara Time", "text": "(UTC+04:00) Samara, Ulyanovsk, Saratov", "offset": 4 },
  { "value": "Iran Standard Time", "text": "(UTC+03:30) Tehran", "offset": 4.5 },
  { "value": "Arabian Standard Time", "text": "(UTC+04:00) Abu Dhabi, Muscat", "offset": 4 },
  { "value": "Azerbaijan Standard Time", "text": "(UTC+04:00) Baku", "offset": 5 },
  { "value": "Mauritius Standard Time", "text": "(UTC+04:00) Port Louis", "offset": 4 },
  { "value": "Georgian Standard Time", "text": "(UTC+04:00) Tbilisi", "offset": 4 },
  { "value": "Caucasus Standard Time", "text": "(UTC+04:00) Yerevan", "offset": 4 },
  { "value": "Afghanistan Standard Time", "text": "(UTC+04:30) Kabul", "offset": 4.5 },
  { "value": "West Asia Standard Time", "text": "(UTC+05:00) Ashgabat, Tashkent", "offset": 5 },
  { "value": "Yekaterinburg Time", "text": "(UTC+05:00) Yekaterinburg", "offset": 5 },
  { "value": "Pakistan Standard Time", "text": "(UTC+05:00) Islamabad, Karachi", "offset": 5 },
  { "value": "India Standard Time", "text": "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi", "offset": 5.5 },
  { "value": "Sri Lanka Standard Time", "text": "(UTC+05:30) Sri Jayawardenepura", "offset": 5.5 },
  { "value": "Nepal Standard Time", "text": "(UTC+05:45) Kathmandu", "offset": 5.75 },
  { "value": "Central Asia Standard Time", "text": "(UTC+06:00) Nur-Sultan (Astana)", "offset": 6 },
  { "value": "Bangladesh Standard Time", "text": "(UTC+06:00) Dhaka", "offset": 6 },
  { "value": "Myanmar Standard Time", "text": "(UTC+06:30) Yangon (Rangoon)", "offset": 6.5 },
  { "value": "SE Asia Standard Time", "text": "(UTC+07:00) Bangkok, Hanoi, Jakarta", "offset": 7 },
  { "value": "N. Central Asia Standard Time", "text": "(UTC+07:00) Novosibirsk", "offset": 7 },
  { "value": "China Standard Time", "text": "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi", "offset": 8 },
  { "value": "North Asia Standard Time", "text": "(UTC+08:00) Krasnoyarsk", "offset": 8 },
  { "value": "Singapore Standard Time", "text": "(UTC+08:00) Kuala Lumpur, Singapore", "offset": 8 },
  { "value": "W. Australia Standard Time", "text": "(UTC+08:00) Perth", "offset": 8 },
  { "value": "Taipei Standard Time", "text": "(UTC+08:00) Taipei", "offset": 8 },
  { "value": "Ulaanbaatar Standard Time", "text": "(UTC+08:00) Ulaanbaatar", "offset": 8 },
  { "value": "North Asia East Standard Time", "text": "(UTC+08:00) Irkutsk", "offset": 8 },
  { "value": "Japan Standard Time", "text": "(UTC+09:00) Osaka, Sapporo, Tokyo", "offset": 9 },
  { "value": "Korea Standard Time", "text": "(UTC+09:00) Seoul", "offset": 9 },
  { "value": "Cen. Australia Standard Time", "text": "(UTC+09:30) Adelaide", "offset": 9.5 },
  { "value": "AUS Central Standard Time", "text": "(UTC+09:30) Darwin", "offset": 9.5 },
  { "value": "E. Australia Standard Time", "text": "(UTC+10:00) Brisbane", "offset": 10 },
  { "value": "AUS Eastern Standard Time", "text": "(UTC+10:00) Canberra, Melbourne, Sydney", "offset": 10 },
  { "value": "West Pacific Standard Time", "text": "(UTC+10:00) Guam, Port Moresby", "offset": 10 },
  { "value": "Tasmania Standard Time", "text": "(UTC+10:00) Hobart", "offset": 10 },
  { "value": "Yakutsk Standard Time", "text": "(UTC+09:00) Yakutsk", "offset": 9 },
  { "value": "Central Pacific Standard Time", "text": "(UTC+11:00) Solomon Is., New Caledonia", "offset": 11 },
  { "value": "Vladivostok Standard Time", "text": "(UTC+10:00) Vladivostok", "offset": 10 },
  { "value": "Sakhalin Standard Time", "text": "(UTC+11:00) Sakhalin", "offset": 11 },
  { "value": "New Zealand Standard Time", "text": "(UTC+12:00) Auckland, Wellington", "offset": 12 },
  { "value": "UTC+12", "text": "(UTC+12:00) Coordinated Universal Time+12", "offset": 12 },
  { "value": "Fiji Standard Time", "text": "(UTC+12:00) Fiji", "offset": 12 },
  { "value": "Magadan Standard Time", "text": "(UTC+12:00) Magadan", "offset": 12 },
  { "value": "Tonga Standard Time", "text": "(UTC+13:00) Nuku'alofa", "offset": 13 },
  { "value": "Samoa Standard Time", "text": "(UTC+13:00) Samoa", "offset": 13 }
];

export const TIMEZONE_OPTIONS = TIMEZONES.map(tz => ({
  value: tz.value,
  label: tz.text
}));